/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'status' : ApplicationStatus,
  'user' : Principal,
  'productName' : string,
  'productType' : ProductType,
  'lender' : string,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type CreditScore = bigint;
export type ProductType = { 'creditCard' : null } |
  { 'businessLoan' : null } |
  { 'personalLoan' : null };
export interface Profile {
  'id' : Principal,
  'pan' : string,
  'created' : bigint,
  'name' : string,
  'incomeRange' : string,
  'email' : string,
  'creditScore' : bigint,
  'mobile' : string,
  'lastLogin' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getAllProfilesSortedByLatestActivity' : ActorMethod<[], Array<Profile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreditScore' : ActorMethod<[Principal], CreditScore>,
  'getMyApplications' : ActorMethod<[], Array<Application>>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, string, string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'submitApplication' : ActorMethod<[ProductType, string, string], undefined>,
  'updateCreditScore' : ActorMethod<[CreditScore], undefined>,
  'updateProfile' : ActorMethod<[string, [] | [bigint]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];