/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Profile = IDL.Record({
  'id' : IDL.Principal,
  'pan' : IDL.Text,
  'created' : IDL.Int,
  'name' : IDL.Text,
  'incomeRange' : IDL.Text,
  'email' : IDL.Text,
  'creditScore' : IDL.Nat,
  'mobile' : IDL.Text,
  'lastLogin' : IDL.Int,
});
export const CreditScore = IDL.Nat;
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ProductType = IDL.Variant({
  'creditCard' : IDL.Null,
  'businessLoan' : IDL.Null,
  'personalLoan' : IDL.Null,
});
export const Application = IDL.Record({
  'status' : ApplicationStatus,
  'user' : IDL.Principal,
  'productName' : IDL.Text,
  'productType' : ProductType,
  'lender' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getAllProfilesSortedByLatestActivity' : IDL.Func(
      [],
      [IDL.Vec(Profile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreditScore' : IDL.Func([IDL.Principal], [CreditScore], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'submitApplication' : IDL.Func([ProductType, IDL.Text, IDL.Text], [], []),
  'updateCreditScore' : IDL.Func([CreditScore], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Opt(IDL.Int)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Profile = IDL.Record({
    'id' : IDL.Principal,
    'pan' : IDL.Text,
    'created' : IDL.Int,
    'name' : IDL.Text,
    'incomeRange' : IDL.Text,
    'email' : IDL.Text,
    'creditScore' : IDL.Nat,
    'mobile' : IDL.Text,
    'lastLogin' : IDL.Int,
  });
  const CreditScore = IDL.Nat;
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ProductType = IDL.Variant({
    'creditCard' : IDL.Null,
    'businessLoan' : IDL.Null,
    'personalLoan' : IDL.Null,
  });
  const Application = IDL.Record({
    'status' : ApplicationStatus,
    'user' : IDL.Principal,
    'productName' : IDL.Text,
    'productType' : ProductType,
    'lender' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getAllProfilesSortedByLatestActivity' : IDL.Func(
        [],
        [IDL.Vec(Profile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreditScore' : IDL.Func([IDL.Principal], [CreditScore], ['query']),
    'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'submitApplication' : IDL.Func([ProductType, IDL.Text, IDL.Text], [], []),
    'updateCreditScore' : IDL.Func([CreditScore], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Opt(IDL.Int)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };